# Fallback roadmaps if LLMs fail

DOMAIN_ROADMAPS = {
    "VLSI & ASIC Design": {
        "domain": "VLSI & ASIC Design",
        "news_headline": "AI hardware accelerators are driving a 400% surge in VLSI and Custom Silicon demand.",
        "beginner_steps": [
            {"title": "Digital Logic Fundamentals", "description": "Master boolean algebra, logic gates, and basic combinational/sequential circuits.", "key_skills": ["Boolean Algebra", "Logic Gates", "K-Maps"], "course_link": "https://www.coursera.org/learn/digital-systems", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm"},
            {"title": "Introduction to Verilog", "description": "Write basic modules, testbenches, and understand simulation.", "key_skills": ["Verilog", "ModelSim", "Testbenches"], "course_link": "https://www.coursera.org/learn/fpga-intro", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNAtzSjM15jM5v9zD2h-lR8h"},
            {"title": "Computer Architecture Basics", "description": "Understand ALU design, registers, and basic memory mapping.", "key_skills": ["Architecture", "ALU", "Registers"], "course_link": "https://www.coursera.org/learn/comparch", "youtube_link": "https://www.youtube.com/playlist?list=PL5PHm2jkkXmidJOd59REog9jdnWfBT9W7"},
            {"title": "FPGA Prototyping", "description": "Implement simple designs on a basic FPGA board.", "key_skills": ["Basys 3", "Vivado", "Synthesis"], "course_link": "https://www.coursera.org/specializations/fpga-design", "youtube_link": "https://www.youtube.com/playlist?list=PLuS_I62o_X9O_nLwS_5VjXzD9xU5qI6O_"},
            {"title": "Basic State Machines", "description": "Design and simulate Moore and Mealy Finite State Machines.", "key_skills": ["FSMs", "State Diagrams", "RTL"], "course_link": "https://www.coursera.org/learn/electronics", "youtube_link": "https://www.youtube.com/playlist?list=PLrY508WwXmX2_E0X_nE9_zQkQ_D_w_L-M"}
        ],
        "intermediate_steps": [
            {"title": "Advanced RTL Design", "description": "Design complex datapaths and controllers for custom hardware.", "key_skills": ["RTL Coding", "Datapaths", "Pipelining"], "course_link": "https://www.coursera.org/learn/vlsicad", "youtube_link": "https://www.youtube.com/playlist?list=PLP_MIsW0wBmfWn-Lw8KshGv_Wn08-4B_F"},
            {"title": "SystemVerilog for Design", "description": "Transition to SystemVerilog constructs for cleaner hardware modeling.", "key_skills": ["SystemVerilog", "Interfaces", "Structs"], "course_link": "https://www.coursera.org/learn/asic-design", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNA_E6_vC7U_f_2-O-NlXqW9"},
            {"title": "Static Timing Analysis (STA)", "description": "Understand setup/hold times and fix timing violations.", "key_skills": ["STA", "Timing Constraints", "PrimeTime"], "course_link": "https://www.coursera.org/learn/physical-design", "youtube_link": "https://www.youtube.com/playlist?list=PLP_MIsW0wBmdU_n_K6f4WpW-YI0tB-p1R"},
            {"title": "Basic Physical Design", "description": "Learn floorplanning, placement, and basic routing concepts.", "key_skills": ["Floorplanning", "P&R", "Innovus"], "course_link": "https://www.coursera.org/learn/vlsi-cad-logic", "youtube_link": "https://www.youtube.com/playlist?list=PLP_MIsW0wBmexXwS090h9WkF1f-Y2I1B0"},
            {"title": "Custom Core Project", "description": "Build and verify a basic pipelined RISC-V or MIPS core.", "key_skills": ["RISC-V", "Pipelining", "Computer Architecture"], "course_link": "https://www.coursera.org/learn/arm-education-digital-logic", "youtube_link": "https://www.youtube.com/playlist?list=PL5PHm2jkkXmidJOd59REog9jdnWfBT9W7"}
        ],
        "advanced_steps": [
            {"title": "Universal Verification Methodology", "description": "Master industry-standard UVM for verifying massive SoCs.", "key_skills": ["UVM", "OVM", "SystemVerilog Assertions"], "course_link": "https://www.coursera.org/specializations/embedded-system-design", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Low Power Design (UPF)", "description": "Implement power gating, clock gating, and multi-Vdd designs.", "key_skills": ["UPF", "Clock Gating", "Low Power"], "course_link": "https://www.coursera.org/learn/power-electronics", "youtube_link": "https://www.youtube.com/playlist?list=PLP_MIsW0wBmdfXvS-V-7G-0u8v1-p-D0H"},
            {"title": "Advanced Physical Design", "description": "Handle complex clock tree synthesis (CTS) and IR drop analysis.", "key_skills": ["CTS", "IR Drop", "EM Analysis"], "course_link": "https://www.coursera.org/learn/vlsi-design", "youtube_link": "https://www.youtube.com/playlist?list=PLP_MIsW0wBmccM-uW7O-L2U-U-p-V-C-D"},
            {"title": "Tape-out Signoff", "description": "Perform rigorous LVS, DRC, and ERC checks before manufacturing.", "key_skills": ["Calibre", "DRC/LVS", "Signoff"], "course_link": "https://www.coursera.org/learn/nanotechnology", "youtube_link": "https://www.youtube.com/playlist?list=PLP_MIsW0wBmceY-U-p-V-C-D-m-uW7O-L2U"},
            {"title": "Silicon Bring-up", "description": "Test and validate actual manufactured silicon in the lab.", "key_skills": ["Post-Silicon Validation", "Oscilloscopes", "JTAG"], "course_link": "https://www.coursera.org/learn/iot", "youtube_link": "https://www.youtube.com/playlist?list=PLP_MIsW0wBmdfXvS-V-7G-0u8v1-p-D0H"}
        ]
    },
    "Embedded Systems & Firmware": {
        "domain": "Embedded Systems & Firmware",
        "news_headline": "The explosive growth of IoT and Automotive EVs is making Embedded Firmware the most critical layer of tech.",
        "beginner_steps": [
            {"title": "C Programming Mastery", "description": "Deep dive into pointers, memory management, and bitwise operations.", "key_skills": ["C", "Pointers", "Bitwise Math"], "course_link": "https://www.coursera.org/learn/c-programming", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Microcontroller Architecture", "description": "Understand memory maps, registers, and the CPU pipeline.", "key_skills": ["MCU Architecture", "Registers", "Memory Maps"], "course_link": "https://www.coursera.org/learn/introduction-embedded-systems", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm"},
            {"title": "Bare-Metal GPIO", "description": "Write basic drivers to control LEDs and read buttons without libraries.", "key_skills": ["GPIO", "Bare-Metal", "Registers"], "course_link": "https://www.coursera.org/learn/embedded-software-hardware", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Interrupts & Timers", "description": "Implement Interrupt Service Routines (ISRs) and hardware timers.", "key_skills": ["ISRs", "Timers", "NVIC"], "course_link": "https://www.coursera.org/learn/embedded-systems-microcontrollers", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Basic Protocols (UART)", "description": "Implement serial communication to print debug messages to a PC.", "key_skills": ["UART", "Serial Monitor", "Baud Rates"], "course_link": "https://www.coursera.org/learn/interface-with-arduino", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"}
        ],
        "intermediate_steps": [
            {"title": "Advanced Hardware Protocols", "description": "Write custom drivers for SPI and I2C sensors.", "key_skills": ["I2C", "SPI", "Logic Analyzers"], "course_link": "https://www.coursera.org/learn/embedded-interface-design", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Direct Memory Access (DMA)", "description": "Offload data transfers from the CPU to DMA controllers.", "key_skills": ["DMA", "Performance Optimization", "Bus Matrix"], "course_link": "https://www.coursera.org/learn/embedded-system-design-uc-boulder", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Real-Time Operating Systems", "description": "Implement FreeRTOS, tasks, queues, and mutexes.", "key_skills": ["FreeRTOS", "Multithreading", "Semaphores"], "course_link": "https://www.coursera.org/learn/real-time-embedded-systems", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Low Power Modes", "description": "Optimize firmware to run on coin cell batteries for years.", "key_skills": ["Sleep Modes", "Power Profiling", "RTC"], "course_link": "https://www.coursera.org/learn/iot-devices", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Wireless IoT Node", "description": "Build a device that connects to Wi-Fi/BLE and sends MQTT data.", "key_skills": ["ESP32/STM32", "MQTT", "Wi-Fi/BLE"], "course_link": "https://www.coursera.org/learn/iot-wireless-communications", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"}
        ],
        "advanced_steps": [
            {"title": "Embedded Linux (Yocto)", "description": "Build custom Linux distributions for embedded processors like Raspberry Pi.", "key_skills": ["Yocto", "Device Trees", "Kernel Modules"], "course_link": "https://www.coursera.org/learn/embedded-linux-interface-design", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Automotive AUTOSAR", "description": "Learn the strict automotive software architecture standard.", "key_skills": ["AUTOSAR", "CAN Bus", "MCAL"], "course_link": "https://www.coursera.org/learn/electric-vehicles-and-mobility", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Over-The-Air (OTA) Updates", "description": "Implement secure, failsafe remote firmware updates.", "key_skills": ["OTA", "Bootloaders", "Cryptography"], "course_link": "https://www.coursera.org/learn/cyber-security-embedded-systems", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Hardware Security Modules", "description": "Utilize HSMs for secure boot, encryption, and secure storage.", "key_skills": ["Secure Boot", "HSM", "AES/RSA"], "course_link": "https://www.coursera.org/learn/hardware-security", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Safety Critical Systems", "description": "Design firmware adhering to ISO 26262 or DO-178C standards.", "key_skills": ["MISRA C", "ISO 26262", "Functional Safety"], "course_link": "https://www.coursera.org/learn/software-security", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"}
        ]
    },
    "Robotics & Automation": {
        "domain": "Robotics & Automation",
        "news_headline": "Collaborative robots and AI-driven automation are redefining the global manufacturing landscape.",
        "beginner_steps": [
            {"title": "Robotics Foundations", "description": "Learn kinematics, dynamics, and basic control theory.", "key_skills": ["Kinematics", "Dynamics", "PID"], "course_link": "https://www.coursera.org/specializations/robotics", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "C++/Python for Robotics", "description": "Master the languages used in modern robotics software stacks.", "key_skills": ["C++", "Python", "Linux"], "course_link": "https://www.coursera.org/learn/robotics-perception", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "ROS1 Fundamentals", "description": "Understand the Robot Operating System architecture and nodes.", "key_skills": ["ROS1", "Nodes", "Topics"], "course_link": "https://www.coursera.org/learn/robotics-flight", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Sensors and Actuators", "description": "Interface with IMUs, encoders, and motor controllers.", "key_skills": ["IMU", "Encoders", "Lidar"], "course_link": "https://www.coursera.org/learn/robotics-mobility", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Basic Navigation", "description": "Implement simple pathfinding algorithms like A*.", "key_skills": ["A*", "Pathfinding", "Grid Maps"], "course_link": "https://www.coursera.org/learn/robotics-capstone", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"}
        ],
        "intermediate_steps": [
            {"title": "Advanced ROS2", "description": "Transition to ROS2 for production-grade robotics applications.", "key_skills": ["ROS2", "DDS", "Lifecycle Nodes"], "course_link": "https://www.coursera.org/learn/robotics-flight", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Computer Vision (OpenCV)", "description": "Process image data for object detection and tracking.", "key_skills": ["OpenCV", "Object Detection", "Tracking"], "course_link": "https://www.coursera.org/learn/robotics-perception", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Simultaneous Localization (SLAM)", "description": "Enable robots to map environments while locating themselves.", "key_skills": ["SLAM", "GMapping", "Lidar Odometry"], "course_link": "https://www.coursera.org/learn/robotics-mobility", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "MoveIt! Manipulation", "description": "Plan complex trajectories for robotic arms.", "key_skills": ["MoveIt", "Kinematic Chains", "Grippers"], "course_link": "https://www.coursera.org/learn/robotics-capstone", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Gazebo Simulation", "description": "Build high-fidelity digital twins for robot testing.", "key_skills": ["Gazebo", "URDF", "SDF"], "course_link": "https://www.coursera.org/specializations/robotics", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"}
        ],
        "advanced_steps": [
            {"title": "Autonomous Navigation Stacks", "description": "Implement end-to-end navigation for mobile robots.", "key_skills": ["Nav2", "Costmaps", "Planners"], "course_link": "https://www.coursera.org/learn/robotics-flight", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Reinforcement Learning for Robotics", "description": "Train robots to perform complex tasks using RL.", "key_skills": ["RL", "PyTorch", "Simulation"], "course_link": "https://www.coursera.org/learn/robotics-perception", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Multi-Robot Coordination", "description": "Swarm robotics and fleet management algorithms.", "key_skills": ["Swarm", "Fleet Management", "Networking"], "course_link": "https://www.coursera.org/learn/robotics-mobility", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
            {"title": "Industrial Robot Integration", "description": "Integrate robots with PLCs and factory MES systems.", "key_skills": ["PLC", "SCADA", "MES"], "course_link": "https://www.coursera.org/learn/robotics-capstone", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
            {"title": "Human-Robot Interaction (HRI)", "description": "Design safe and intuitive collaborative robot systems.", "key_skills": ["HRI", "Safety Sensors", "UI/UX"], "course_link": "https://www.coursera.org/specializations/robotics", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"}
        ]
    }
}

GENERIC_ROADMAP = {
    "domain": "Generic Electronics & Communication",
    "news_headline": "The ECE industry is experiencing a massive renaissance as hardware becomes the bottleneck for AI.",
    "beginner_steps": [
        {"title": "Core Fundamentals", "description": "Master Network Theory, Digital Logic, and Basic C.", "key_skills": ["Circuit Analysis", "Digital Logic", "C"], "course_link": "https://www.coursera.org/learn/electronics", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRjMH3mWf6kwqiTbT798eAOm"},
        {"title": "Microcontrollers", "description": "Learn bare-metal programming on Arduino or STM32.", "key_skills": ["Microcontrollers", "Embedded C"], "course_link": "https://www.coursera.org/learn/embedded-software-hardware", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
        {"title": "Basic Protocols", "description": "Understand how hardware talks.", "key_skills": ["UART", "I2C"], "course_link": "https://www.coursera.org/learn/embedded-systems-microcontrollers", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
        {"title": "Simple Projects", "description": "Build a sensor node.", "key_skills": ["Sensors", "Hardware Debugging"], "course_link": "https://www.coursera.org/learn/interface-with-arduino", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
        {"title": "PCB Basics", "description": "Learn to design a simple 2-layer board.", "key_skills": ["KiCad", "Schematics"], "course_link": "https://www.coursera.org/learn/iot", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"}
    ],
    "intermediate_steps": [
        {"title": "Advanced C/C++", "description": "Master pointers and object-oriented embedded code.", "key_skills": ["C++", "Pointers"], "course_link": "https://www.coursera.org/learn/c-plus-plus-introduction", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
        {"title": "RTOS Integration", "description": "Move from superloops to task-based RTOS.", "key_skills": ["FreeRTOS", "Multithreading"], "course_link": "https://www.coursera.org/learn/real-time-embedded-systems", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
        {"title": "Advanced Protocols", "description": "Implement high-speed SPI and CAN.", "key_skills": ["SPI", "CAN Bus"], "course_link": "https://www.coursera.org/learn/embedded-interface-design", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
        {"title": "Complex Portfolios", "description": "Build a connected IoT device.", "key_skills": ["Wi-Fi", "MQTT"], "course_link": "https://www.coursera.org/learn/iot-wireless-communications", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
        {"title": "Scripting", "description": "Automate hardware tests with Python.", "key_skills": ["Python", "PySerial"], "course_link": "https://www.coursera.org/learn/python", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"}
    ],
    "advanced_steps": [
        {"title": "System Architecture", "description": "Design end-to-end hardware/software systems.", "key_skills": ["Architecture", "System Design"], "course_link": "https://www.coursera.org/learn/embedded-system-design-uc-boulder", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
        {"title": "Embedded Linux", "description": "Write drivers for the Linux kernel.", "key_skills": ["Linux Kernel", "Device Trees"], "course_link": "https://www.coursera.org/learn/embedded-linux-interface-design", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
        {"title": "Hardware Acceleration", "description": "Offload algorithms to FPGAs.", "key_skills": ["FPGA", "Verilog"], "course_link": "https://www.coursera.org/specializations/fpga-design", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"},
        {"title": "High-Speed PCB", "description": "Design 6+ layer boards with impedance control.", "key_skills": ["Altium", "Signal Integrity"], "course_link": "https://www.coursera.org/learn/vlsicad", "youtube_link": "https://www.youtube.com/playlist?list=PLvG6Y3kU-uNDP0z6vF8H7K2_f9U-O6U1j"},
        {"title": "Industry Certification", "description": "Master safety standards and secure coding.", "key_skills": ["MISRA", "Secure Boot"], "course_link": "https://www.coursera.org/learn/hardware-security", "youtube_link": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuK5QxtdRNzP"}
    ]
}
